//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCup_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldCup_WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poništi.
        /// </summary>
        public static string btnCancelText {
            get {
                return ResourceManager.GetString("btnCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        public static string btnSaveText {
            get {
                return ResourceManager.GetString("btnSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled.
        /// </summary>
        public static string btnView {
            get {
                return ResourceManager.GetString("btnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrvatski.
        /// </summary>
        public static string cbCro {
            get {
                return ResourceManager.GetString("cbCro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string cbEng {
            get {
                return ResourceManager.GetString("cbEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string lbCancel {
            get {
                return ResourceManager.GetString("lbCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrditi?.
        /// </summary>
        public static string lbConfirm {
            get {
                return ResourceManager.GetString("lbConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir prvenstva.
        /// </summary>
        public static string lbCup {
            get {
                return ResourceManager.GetString("lbCup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neodlučenih:.
        /// </summary>
        public static string lbDraws {
            get {
                return ResourceManager.GetString("lbDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFA kod:.
        /// </summary>
        public static string lbFifa {
            get {
                return ResourceManager.GetString("lbFifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj odigranih utakmica:.
        /// </summary>
        public static string lbGamesPlayed {
            get {
                return ResourceManager.GetString("lbGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlika:.
        /// </summary>
        public static string lbGoalDifference {
            get {
                return ResourceManager.GetString("lbGoalDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj golova primljenih:.
        /// </summary>
        public static string lbGoalsReceived {
            get {
                return ResourceManager.GetString("lbGoalsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj golova zabijenih:.
        /// </summary>
        public static string lbGoalsScored {
            get {
                return ResourceManager.GetString("lbGoalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        public static string lbLanguage {
            get {
                return ResourceManager.GetString("lbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poraza:.
        /// </summary>
        public static string lbLosses {
            get {
                return ResourceManager.GetString("lbLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapetan:.
        /// </summary>
        public static string lbPlayerCaptain {
            get {
                return ResourceManager.GetString("lbPlayerCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj golova:.
        /// </summary>
        public static string lbPlayerGoals {
            get {
                return ResourceManager.GetString("lbPlayerGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime i prezime:.
        /// </summary>
        public static string lbPlayerName {
            get {
                return ResourceManager.GetString("lbPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj:.
        /// </summary>
        public static string lbPlayerNumber {
            get {
                return ResourceManager.GetString("lbPlayerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija:.
        /// </summary>
        public static string lbPlayerPosition {
            get {
                return ResourceManager.GetString("lbPlayerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj žutih kartona:.
        /// </summary>
        public static string lbPlayerYellowCards {
            get {
                return ResourceManager.GetString("lbPlayerYellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezolucija.
        /// </summary>
        public static string lbResolution {
            get {
                return ResourceManager.GetString("lbResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REZULTAT:.
        /// </summary>
        public static string lbResult {
            get {
                return ResourceManager.GetString("lbResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi reprezentaciju....
        /// </summary>
        public static string lbTeam1 {
            get {
                return ResourceManager.GetString("lbTeam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi protivnika....
        /// </summary>
        public static string lbTeam2 {
            get {
                return ResourceManager.GetString("lbTeam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv:.
        /// </summary>
        public static string lbTeamName {
            get {
                return ResourceManager.GetString("lbTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobjeda:.
        /// </summary>
        public static string lbWins {
            get {
                return ResourceManager.GetString("lbWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žensko.
        /// </summary>
        public static string rbFemaleText {
            get {
                return ResourceManager.GetString("rbFemaleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muško.
        /// </summary>
        public static string rbMaleText {
            get {
                return ResourceManager.GetString("rbMaleText", resourceCulture);
            }
        }
    }
}
